export enum ErrorCode {
  APP_VERSION_NOT_FOUND = 'APP_VERSION_NOT_FOUND',
  APP_VERSION_NOT_ALLOWED = 'APP_VERSION_NOT_ALLOWED',
  APP_MAINTENANCE = 'APP_MAINTENANCE',

  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_USER_INACTIVE = 'AUTH_USER_INACTIVE',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
}
