export enum ErrorCode {
  PLATFORM_VERSION_NOT_FOUND = 'PLATFORM_VERSION_NOT_FOUND',
  PLATFORM_VERSION_NOT_ALLOWED = 'PLATFORM_VERSION_NOT_ALLOWED',
  PLATFORM_MAINTENANCE = 'PLATFORM_MAINTENANCE',
}
